apiVersion: v1
kind: Service
metadata:
  name: nginx-vts-exporter
  namespace: demo-apps
  labels: { app: nginx }
spec:
  selector: { app: nginx }
  ports:
    - name: metrics
      port: 9913
      targetPort: 9913
