apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-vts-config
  namespace: demo-apps
data:
  nginx.conf: |
    worker_processes 1;
    events { worker_connections 1024; }
    http {
      vhost_traffic_status_zone;
      server {
        listen 80;
        location / {
          root /usr/share/nginx/html;
          index index.html;
        }
        location /status {
          vhost_traffic_status_display;
          vhost_traffic_status_display_format json;
        }
      }
    }
