apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: apache-mtail-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - demo-apps
  selector:
    matchLabels:
      app: apache
  endpoints:
    - port: metrics
      interval: 15s
